weba:
  build: .
  volumes:
    - .:/home_on_rails
  expose:
    - 3000
  ports:
    - 3000:3000
  links:
    - db
db:
  image: mysql/mysql-server
  expose:
   - 3306
  environment:
    MYSQL_DATABASE: home_on_rails
    MYSQL_USER: home_on_rails
    MYSQL_PASSWORD: root
    MYSQL_ROOT_PASSWORD: root