web:
  build: .
  volumes:
    - .:/home_on_rails
  ports:
    - "3000:3000"
  links:
    - db
db:
  image: library/mysql:5.6.22
  ports:
    - "13306:3306"
  environment:
    MYSQL_DATABASE: home_on_rails
    MYSQL_USER: home_on_rails
    MYSQL_PASSWORD: root
    MYSQL_ROOT_PASSWORD: root